### ISSUE TITLE
RuntimeError: Method `model.to_yaml()` has been removed due to security risk of arbitrary code execution. Please use `model.to_json()` instead

### ISSUE THREAD

**Issue by Joyce121** [frankchen121212/RHSNet#3]
![截图20221008194457](https://user-images.githubusercontent.com/115353880/194707831-fa4c5da3-7649-43a0-adf1-28a11b208356.png)

when I run  this command "python motif_extractor.py experiments/nature_genetics_2008/1000_4/CNN/baseline_classification.json", everything was fine in the early time. When the simulation is complete, appear "[2022-10-08 17:54:19,785][line: 28] ==> saving =>/projects/software/RHSNet/model/EAS/CNN/1000_4/EAS.json" ,  the software reported this error,"
RuntimeError: Method `model.to_yaml()` has been removed due to security risk of arbitrary code execution. Please use `model.to_json()` instead.", I don't know how to fix it .

![截图20221008194539](https://user-images.githubusercontent.com/115353880/194707823-4956d64b-0061-4d29-b768-44e5553300fe.png)

**Comment by frankchen121212** [comment]
Hello, Joyce. Thank you for your interest in RHSNet,

Sorry for the late reply,

It seems to be a Tensorflow version problem.  Before running the experiments, please make sure that you have the following requirements: tensorflow-gpu==1.12.0, keras==2.2.4, cudatoolkit==9.0, and cudnn=7.1.2


You can install the right version of TensorFlow in the virtual environment with the following command
```
conda install tensorflow-gpu==1.12.0 keras==2.2.4 cudatoolkit==9.0 cudnn=7.1.2 h5py

```

A higher version of TensorFlow will cause this problem. Refer to: https://github.com/devanshkv/fetch/issues/22

If you still have a problem, please share your TensorFlow version as well as your Keras version. Thank you.
