### ISSUE TITLE
RuntimeError: tf.placeholder() is not compatible with eager execution

### ISSUE THREAD

**Issue by Joyce121** [frankchen121212/RHSNet#4]
When I run the example command 

"python motif_extractor.py experiments/nature_genetics_2008/1000_4/CNN/baseline_classification.json"

the RHSNet reported ”RuntimeError: tf.placeholder() is not compatible with eager execution“

**Comment by Joyce121** [comment]
![Uploading 333333.png…]()

**Comment by frankchen121212** [comment]
Dear Joyce,

According to your last issue, I assume that you are using Tensorflow v2.0 and higher,

Assume you are using Tensorflow 2.0 preview release which has eager execution enabled by default. There is a disable_eager_execution() in v1 API, which you can put in the front of your code like:
```
import tensorflow as tf

tf.compat.v1.disable_eager_execution()

```
Or, you need to downgrade your Tensorflow version to v1.12 according to README

```
conda install tensorflow-gpu==1.12.0 keras==2.2.4 cudatoolkit==9.0 cudnn=7.1.2 h5py

```
