### ISSUE TITLE
How can I predict recombination hotspot by this program

### ISSUE THREAD

**Issue by Joyce121** [frankchen121212/RHSNet#5]

**Comment by frankchen121212** [comment]
Hi, thank you for your comment.

Please refer to this previously answered reply to a similar question:

https://github.com/frankchen121212/RHSNet/issues/2

**Comment by Joyce121** [comment]
Thanks, but I still don't know how to reduce the "X.npy, Y.npy and L.npy" of my data to predict motifs, can you tell me please.




Joyce
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "frankchen121212/RHSNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月30日(星期五) 上午9:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [frankchen121212/RHSNet] How can I predict recombination hotspot by this program (Issue #5)





 
Closed #5 as completed.
