### ISSUE TITLE
How can I predict motifs using my data  by this program

### ISSUE THREAD

**Issue by Joyce121** [frankchen121212/RHSNet#6]

**Comment by Joyce121** [comment]
I don't know how to reduce the "X.npy   Y.npy and  L.npy " of my data , can you help me ? Thanks a lot.

**Comment by frankchen121212** [comment]
Thank you for your interest in RHSNet,

The X.npy is a numpy array storing the one-hot matrix of the input DNA sequences, with 1000bps max length. The Y.npy stores the label of your sequences, hotspots or not. The L.npy stores the length of your sequences.

Suppose you have 500 sequences with unknown label.

First, you can load the pre-trained weight trained by from [Google Drive](https://drive.google.com/drive/folders/1oafeCEKoWMXoaRpY20leyJnt7uJb0vv7?usp=sharing)

Then you will be able to reverse-engineer the important motif of your data Based on the predicted labels. According to motif_extractor_example.ipynb

Example data format can be found in [Google Drive](https://drive.google.com/drive/folders/1dUY9ZJGexdVGkmDkWhljhTXPPEBRN2wG?usp=sharing)

The X.npy should be in the shape of [N,1000,4], where N is the size of your sequence dataset
The Y.npyshould be in the shape of [N,1], with [0,1] differentiate the coldspot & hotspot 
The L.npy should be in the shape of [N,1].

**Comment by Joyce121** [comment]
Thank you very much, I have the input DNA sequences, with 50000bps, can I use the motif_extractor_example.ipynb to extract the motif, and how?

**Comment by frankchen121212** [comment]
As the sequences are too long, you might crop them into fifty 1000bp sequences and conduct the previously mentioned analysis.

**Comment by Joyce121** [comment]
Thank you, your suggestion is effective, but too many sequences cause the program can not run, how should I solve it

**Comment by frankchen121212** [comment]
The program can handle as many sequences as possible. as long as they are 1000 bp in length. 

Are you able to run the program with the public dataset we provided?

**Comment by Joyce121** [comment]
python /gpfs/home/wangsheng/wangms/06.Liuzx_Projects/00_recomb_rate/RHSNet/motif_extractor.py  /gpfs/home/wangsheng/wangms/06.Liuzx_Projects/00_recomb_rate/RHSNet/experiments/human_science_2019/1000_4/CNN/baseline_classification.json

**Comment by Joyce121** [comment]
TH你好

**Comment by Joyce121** [comment]
当我序列过多时，会报错Traceback (most recent call last):
  File "/gpfs/home/wangsheng/wangms/06.Liuzx_Projects/00_recomb_rate/RHSNet/motif_extractor.py", line 341, in <module>
    recomb_rate = recomb_rates[idx]
IndexError: index 20000 is out of bounds for axis 0 with size 20000

**Comment by Joyce121** [comment]
另外，直接使用我的数据进行motif 预测时，报错为 File "motif_extractor.py", line 84, in get_rate
    rate_mat.append(d[char_rate])
KeyError: 'rate'  但如果我用公共数据在motif 文件夹下生成了recomb_rate.npy 时，便可正常运行

**Comment by Joyce121** [comment]
I get an error when I have too many sequences， how can I resolve that?


Traceback (most recent call last):
File "/gpfs/home/wangsheng/wangms/06.Liuzx_Projects/00_recomb_rate/RHSNet/motif_extractor.py", line 341, in
recomb_rate = recomb_rates[idx]
IndexError: index 20000 is out of bounds for axis 0 with size 20000

**Comment by Joyce121** [comment]
in addition, when using my data directly for motif prediction, the error is

 File "motif_extractor.py", line 84, in get_rate
rate_mat.append(d[char_rate])
KeyError: 'rate' 

But if I generate recomb_rate.npy in the motif folder with the public data, it works fine, I use my data and the recomb_rate.npy of public data  to predict motif, is that ok?
